const cardContentStyles = {
    title: {
        fontFamily: 'Karla',
        fontStyle: 'normal',
        fontWeight: '500',
        fontSize: '17px',
        color: '#666666',
    },
    mainElement: {
        fontFamily: 'Karla',
        fontStyle: 'normal',
        fontWeight: '600',
        fontSize: '28px',
        color: '#222222',
    },
    secondryElement: {
        fontFamily: 'Karla',
        fontStyle: 'normal',
        fontWeight: '600',
        fontSize: '22px',
        color: '#222222',
        display: 'flex',
        alignItems: 'center',
        wordBreak: 'break-all',
    },
    addressSecondryElement: {
        fontFamily: 'Karla',
        fontStyle: 'normal',
        fontWeight: '600',
        fontSize: '22px',
        color: '#222222',
        display: 'flex',
        alignItems: 'center',
    },
    profit: {
        fontFamily: 'Karla',
        fontStyle: 'normal',
        fontWeight: 'normal',
        fontSize: '13px',
        color: '#31AD65',
        margin: '0px 4px',
    },
    loss: {
        fontFamily: 'Karla',
        fontStyle: 'normal',
        fontWeight: 'normal',
        fontSize: '13px',
        color: '#DA1818',
        margin: '0px 4px',
    },
    lastWeek: {
        fontFamily: 'Karla',
        fontStyle: 'normal',
        fontWeight: 'normal',
        fontSize: '13px',
        color: '#666666',
        margin: '0px 4px',
    },
    reduceGraphSize: { padding: '5px' },
    card1: {
        borderRadius: '0px',
    },
    card2: {
        borderRadius: '0px',
    },
    modalCardHeader: {
        fontFamily: 'Source Serif Pro',
        fontStyle: 'normal',
        fontWeight: '600',
        fontSize: '22px',
        lineHeight: '28px',
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        color: '#222222',
    },
    modalCardDescription: {
        fontFamily: 'Karla',
        fontStyle: 'normal',
        fontWeight: '500',
        fontSize: '17px',
        lineHeight: '20px',
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        color: '#222222',
    },

    copyAddressStyle: {
        background: '#EEEEEE',
        fontFamily: 'Karla',
        fontStyle: 'normal',
        fontWeight: '500',
        fontSize: '15px',
        lineHeight: '18px',
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        color: '#666666',
    },
};

export { cardContentStyles };
