//change type=mock for mock data,
// const collaterals =
//   type === "mock" ? ["gZIL", "WZIL", "WBTC"] : ["WZIL", "COL"];
// const allCollaterals =
//   type === "mock" ? ["All", "gZIL", "WZIL", "WBTC"] : ["All", "WZIL", "COL"];

const collaterals = ['WZIL'];
const allCollaterals = ['All', 'WZIL'];

const dataPath = 'data';
const statPath = 'stat';
// 68.183.87.16

module.exports = {
    WALLET_CONNECT: 'Connect Wallet',
    MY_VAULTS: 'MY VAULTS',
    // BACKEND_SERVICE: `http://54.254.118.51/${dataPath}/`,
    BACKEND_SERVICE: `https://api-launch.pillarprotocol.com/${dataPath}/`,
    // BACKEND_STAT_SERVICE: `http://54.254.118.51/${statPath}/`,
    BACKEND_STAT_SERVICE: `https://api-launch.pillarprotocol.com/${statPath}/`,
    COLLATERALS_TEXT: 'COLLATERALS',
    COLLATERALS: collaterals,
    DASHBOARD_HEADER: 'Pillar Dashboard',
    LAST_WEEK_TEXT: 'Past Week',
    TOTAL_COLLATERAL_LOCKED_TEXT: 'Total Collateral Locked',
    TOTAL_PILLAR_LOCKED_TEXT: 'Total Pillar Borrowed',
    TOTAL_PILLAR_REPAID_TEXT: 'Total Pillar Repaid',
    TOTAL_VALUE_LOCKED_TEXT: 'Approx Value of Collaterals Locked',
    RECENT_TRANSACTIONS: 'RECENT TRANSACTIONS',
    ALL_COLLATERALS: allCollaterals,
    ALL_COLLATERALS_TEXT: 'ALL COLLATERALS',
    VIEW_ALL_TRANSACTIONS: 'VIEW ALL TRANSACTIONS',
    DASHBOARD_TABLE_COLUMNS: ['timestamp', 'txn hash', 'vault id', 'amount', 'collateral', 'operation'],
    MINIMUM_COLLATERAL: 'MINIMUM COLLATERAL',
    INTEREST_RATE: 'INTEREST RATE',
    LIQUIDATION_RATIO: 'LIQUIDATION RATIO',
    LIQUIDATION_VALUE: 'LIQUIDATION VALUE',
    TOTAL_VAULTS: 'TOTAL VAULTS',
    VAULTS_OCCUPIED: 'VAULTS OCCUPIED',
    VAULTS_REMAINING: 'VAULTS REMAINING',
    FACTORY_FEATURES: ['Create Vault'],
    FACTORY_TABLE_COLUMNS: ['created', 'vault id', 'collateral locked', 'pillar borrowed', 'owner'],
    VIEW_ALL_VAULTS: 'VIEW ALL VAULTS',
    DASHBOARD_FEATURES: [],
    VAULT_OWNER_FEATURES: ['Add Collateral', 'Borrow Pillar', 'Repay Pillar', 'Release Collateral'],
    VAULT_NON_OWNER_FEATURES: ['Liquidate Vault'],
    VAULT_TABLE_COLUMNS: ['timestamp', 'txn hash', 'operation', 'amount'],
    VAULT_ADDRESS: 'VAULT ADDRESS',
    VAULT_ID: 'VAULT ID',
    VAULT_FACTORY: 'VAULT FACTORY',
    TOTAL_DEBT: 'TOTAL DEBT',
    OWNER_ADDRESS: 'OWNER ADDRESS',
    INTEREST_ACCUMULATED: 'INTEREST ACCUMULATED',
    CREATE_VAULT_TEXT: 'CREATE VAULT',
    ENTER_COLLATERAL_AMOUNT_TEXT: 'ENTER COLLATERAL AMOUNT',
    ENTER_PILLAR_AMOUNT_TEXT: 'ENTER PILLAR AMOUNT',
    APPROVE_COLLATERAL_TEXT: 'APPROVE COLLATERAL',
    APPROVE_COLLATERAL_DESC: 'Enter the collateral amount to approve',
    COLLATERAL_APPROVED_TEXT: 'COLLATERAL APPROVED',
    CANCEL_TEXT: 'CANCEL',
    BACK_TO_CREATE_VAULT: 'Back to create vault',
    ADD_COLLATERAL_TEXT: 'ADD COLLATERAL',
    ADD_COLLATERAL_REQUEST_TEXT: 'Enter the amount of collateral to be deposited to the vault',
    ADD_COLLATERAL_DONE: 'Done',
    BORROW_PILLAR_TEXT: 'BORROW PILLAR',
    YOUR_WALLET_ADDRESS: 'Your wallet address',
    USE_YOUR_OWN_VAULT: 'Copy your wallet address',
    AMOUNT_TO_BORROW: 'Amount to Borrow',
    AMOUNT_TO_RELEASE: 'Amount to be released ',
    LOADING_BORROW: 'Borrowing',
    LOADING_RELEASE: 'Releasing',
    ADDING_COLLATERAL: 'Adding Collateral',
    ADDED_COLLATERAL: 'Added Collateral',
    PILLAR_SYMBOL: 'PIL',
    DOLLAR_SYMBOL: '$',
    DOLLAR: 'USD',
    MINT_PILLAR_WARNING: 'You can only mint pillar till collateralization ratio is more than liquidation ratio',
    RELEASE_COLLATERAL_WARNING: 'Make sure you have sufficient collateral in vault to prevent liquidation',
    RECOMMENDED_PILLAR_MINT_TEXT: 'Recommended Value',
    RECOMMENDED_RELEASE_COLLATERAL_TEXT: 'Safe Value',
    REPAY_DEBT: 'Repay Pillar',
    REPAY_ALL: 'Repay Total Debt',
    REPAY_PARTIAL: 'Repay Partial Debt',
    REPAY_LOADING: 'Repaying',
    ADD_COLLATERAL_OPERATION: 'Add Collateral',
    REMOVE_COLLATERAL_OPERATION: 'Remove Collateral',
    REPAY_OPERATION: 'Repay',
    LIQUIDATE_OPERATION: 'Liquidate',
    LIQUIDATE_VAULT: 'Liquidate Vault',
    LIQUIDATING: 'Liquidating',
    LIQUIDATION_SUCCESS: 'Liquidation Success',
    NETWORK: 'mainnet',
    PILLAR_AVAILABLE_FOR_REPAY: 'Pillar Available For Repaying',
    PILLAR_AVAILABLE: 'Pillar Available',
    PILLAR_APPROVERD: 'Pillar Approved',
    APPROVE_PILLAR: 'Approve Pillar',
    APPROVE_PILLAR_DESCRIPTION: 'Allow Vault factory to use pillar in your account for repaying',
    APPROVE_DIFFERENCE: 'Approve Difference',
    PLACE_LIQUIDATION_REQUEST: 'Place Liquidation Request',
    LIQUIDATION_APPROVED: 'Your Liquidation Request has been approved',
    PILLAR_APPROVE_REQUEST_TEXT: 'Enter Pillar amount to approve',
    BACK_TO_LIQUIDATION: 'Back to liquidate vault',
    NOT_ENOUGH_PILLAR: 'You do not have enough pillar approved for liquidating the vault',
    COLLATERAL_APPROVED_SUCCESS: 'The collateral shall be deposited in vault directly',
    COLLATERAL_APPROVED_LABEL: 'Collateral Approved:',
    CREATE_VAULT_LOADING_START: 'Creating your vault for',
    COLLATERL_END: 'collateral...',
    CREATE_VAULT_SUCCESS: 'Your vault has been created.',
    APPROVE_COLLATERAL_LOAD: 'Approving',
    REPAY_SUCCESS_START: 'Your debt of',
    REPAY_SUCCESS_END: 'PIL has been repaid.',
    APPROVE_PILLAR_SUCCESS: 'Your Pillar has been approved.',
    APPROVE_PILLAR_ERROR: 'Request to liquidate vault failed. Please try again.',
    DASHBOARD_REFRESH_INTERVAL: 120000,
    VAULT_FACTORY_REFRESH_INTERVAL: 120000,
    PRINCIPLE: 'Principle',
    INTEREST: 'Interest',
    NEW_VAULT_MESSAGE: 'New Vault has been created and shall be visible in your MyVaults dropdown',
    REPAY_DESCRIPTION: 'Deposit Pillar before Repaying',
    COLLATERAL_ONCHAIN_DATA: {
        WZIL: {
            tokenAddress: '0x4306f921c982766810cf342775fd79aa2d0d0e24'.toLowerCase(),
            factory: '0x323e8105ba12d46e38d31cd674b6a2d16d76e6d1'.toLowerCase(),
            proxy: '0xa9660ac4f5751d9e02605992df512434697dd449'.toLowerCase(),
        },
        // COL: {
        //   factory: "0x5587a0b6683E6Ce8D665fD8FAc79635D27bd7C12",
        //   tokenAddress: "0xB6095986f4F6DFCF0379238875c4Be9aCaFF1714",
        // },
    },
    PILLAR_TOKEN_ADDRESS: '0x65211495ad83e9959f775bbe2bd7feb7c83c4f1a',
    GZIL_TOKEN_ADDRESS: '0xa845C1034CD077bD8D32be0447239c7E4be6cb21'.toLowerCase(),
    GZIL_STAKING: '0x45CeABeB309a1210608080e124690C3913b41147'.toLowerCase(),
    GZIL_DELEGATION: '0x52473d1e65842336132a62A2A2F5Fa72a9007e96'.toLowerCase(),
    REWARD_CONTRACT: '0x4DE67C4Db8dBD2Eeb6F8037eD779D31bD9991DA4'.toLowerCase(),
    DECIMAL: {
        WZIL: 12,
        // COL: 18,
        PIL: 6,
        TOTAL_COLLATERAL: 2,
        COL_RATIO: 2,
        ZIL: 12,
        GZIL: 15,
    },
    TRANSACTIONS_HEADER: 'Transactions',
    RELEASE_COLLATERAL_TEXT: 'Release Collateral',
    WZIL_SPECIFIC_FEATURES: ['ZIL->WZIL', 'WZIL->ZIL'],
    ZIL_TO_WZIL: 'ZIL->WZIL',
    WZIL_TO_ZIL: 'WZIL->ZIL',
    CONVERTING: 'Converting',
    ZIL_SYMBOL: 'ZIL',
    GZIL_SYMBOL: 'GZIL',
    SHARES_SYMBOL: 'stkd-gzil',
    AMOUNT_TO_CONVERT: 'Amount to convert',
    PRICE_SYMBOLS: {
        ZILUSDT: 'USD',
    },
    WARNINGCONSENT: `By checking the below box I understand that the Pillar Protocol code (https://viewblock.io/zilliqa/address/zil102wnukht6tkalgdc3v7fw3llhpu800ft943la8?tab=code,https://viewblock.io/zilliqa/address/zil13ls52yyyx68n6gvrpq24lwezgvrjdjh0ueehar?tab=code) and the current website has not been audited by a third party. I understand that by using such software, I run the risk of losing all my funds. I willingly take this risk to partake in the usage of the Pillar Protocol and I waive all rights if any loss results from me using the Pillar Protocol.`,
    STAKING: 'Staking',
    STAKING_FEATURES: ['LOCK TOKENS', 'DELEGATE', 'REQUEST UNLOCK'],
    LOCK_TOKENS: 'LOCK TOKENS',
    DELEGATE_STAKE: 'DELEGATE',
    REQUEST_UNLOCK_TOKENS: 'REQUEST UNLOCK',
    WITHDRAW_TOKENS: 'WITHDRAW',
    CANCEL_UNLOCK_REQUEST: 'CANCEL UNLOCK',
    ENTER_GZIL_TOKEN: 'Enter GZIL to lock in staking contract',
    ADD_GZIL_TOKENS: 'Lock GZIL Tokens',
    APPROVE_GZIL: 'Approve GZIL Tokens',
    LOCKING_TOKENS: 'Locking Tokens for staking',
    LOCKED_TOKENS: 'Locked Tokens for staking',
    LOCK_TOKENS_DONE: 'Done',
    STAKING_TOP_DELEGATOR_TABLE_HEADERS: ['Rank', 'Owner', 'Shares'],
    TOKEN_ADDRESS_TO_NAME_MAP: {
        '0xfc96828ccfb2eae68d22dcdc60fae2511e5a04b1': 'GZIL',
    },
};
